---
script: "./script/cibuild"
gemfile: "this/does/not/exist"
rvm:
  - 1.9.3
  - 2.1.1
env:
  global:
    # encrypted GITHUB_API_TOKEN for librarian-puppet
    secure: "sDoHJ4pMaQ9eqCkmoA5nSI43xvWf2ooQVMRvV79QxN0eYL61nUg6yFPSDQW8UdpKRP0VvNYM9mNbSmhpvLkG3S8x2T3bdFYPsfrXtOXJtvh66gc6reQw1fDLc5jisEGNCE+tjKI0xZadFboyk7IK2/EKIIffas4dxaSgVrEItsM="
